"""CostPilot — Report Generator (Markdown + HTML)."""

import os
import logging
from typing import Any
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


class ReportGenerator:
    def __init__(self, config: Any) -> None:
        self.config = config

    def generate(self, costs: dict, sizing: dict, unused: dict, output_dir: str = "report") -> None:
        os.makedirs(output_dir, exist_ok=True)
        md = self._build_markdown(costs, sizing, unused)
        with open(os.path.join(output_dir, "cost-report.md"), "w") as f:
            f.write(md)
        logger.info(f"Report written to {output_dir}/cost-report.md")

    def generate_from_cache(self, output_dir: str = "report") -> None:
        logger.info("Generating from cached data (not implemented — run analyze first)")

    def _build_markdown(self, costs: dict, sizing: dict, unused: dict) -> str:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        total_savings = costs.get("potential_savings", 0) + sizing.get("potential_savings", 0) + unused.get("potential_savings", 0)

        lines = [
            "# ☁️ CostPilot — AWS Cost Optimization Report",
            f"**Generated:** {now}",
            f"**Period:** {costs.get('period', {}).get('start', 'N/A')} to {costs.get('period', {}).get('end', 'N/A')}",
            "",
            "## Executive Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total Spend (period) | **${costs.get('total_spend', 0):,.2f}** |",
            f"| Average Daily | ${costs.get('avg_daily', 0):,.2f} |",
            f"| Projected Monthly | ${costs.get('projected_monthly', 0):,.2f} |",
            f"| Cost Spikes Detected | {len(costs.get('cost_spikes', []))} |",
            f"| **Total Potential Savings** | **${total_savings:,.2f}/month** |",
            "",
            "## Top Services by Spend",
            "",
            "| Service | Monthly Cost |",
            "|---------|-------------|",
        ]

        for svc in costs.get("top_services", []):
            lines.append(f"| {svc['service']} | ${svc['amount']:,.2f} |")

        lines.extend([
            "",
            "## EC2 Rightsizing Recommendations",
            "",
            f"Analyzed {sizing.get('instances_analyzed', 0)} instances (threshold: {sizing.get('cpu_threshold', 30)}% avg CPU)",
            "",
        ])

        recs = sizing.get("recommendations", [])
        if recs:
            lines.extend([
                "| Instance | Current | Recommended | Avg CPU | Monthly Savings |",
                "|----------|---------|-------------|---------|----------------|",
            ])
            for r in recs:
                lines.append(f"| {r['instance_id']} ({r.get('name', '')}) | {r['current_type']} | {r['recommended_type']} | {r['avg_cpu_percent']}% | ${r['monthly_savings']:,.2f} |")
        else:
            lines.append("✅ No rightsizing recommendations — instances are properly sized.")

        lines.extend([
            "",
            "## Unused Resources",
            "",
            f"Found **{unused.get('total_unused', 0)}** unused resources wasting **${unused.get('potential_savings', 0):,.2f}/month**",
            "",
        ])

        for category, items in unused.get("resources", {}).items():
            if items:
                lines.append(f"### {category.replace('_', ' ').title()}")
                lines.append("")
                for item in items[:10]:
                    lines.append(f"- **{item['id']}** ({item['type']}) — ${item.get('monthly_cost', 0):,.2f}/mo — {item.get('action', '')}")
                lines.append("")

        lines.extend([
            "---",
            "*Generated by CostPilot — AWS Cloud Cost Optimization Engine*",
        ])

        return "\n".join(lines)
