"""SentinelGuard — Compliance Report Generator.

Generates compliance summary reports from AWS Config and SecurityHub,
outputs as Markdown for easy reading.
"""

import json
import logging
import os
from datetime import datetime, timezone
from typing import Any

import boto3

logger = logging.getLogger()
logger.setLevel(logging.INFO)

config_client = boto3.client("config")
securityhub = boto3.client("securityhub")
s3 = boto3.client("s3")

REPORT_BUCKET = os.environ.get("REPORT_BUCKET", "sentinelguard-reports")


def handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Generate compliance report and upload to S3."""
    now = datetime.now(timezone.utc)
    
    # Gather compliance data
    config_compliance = _get_config_compliance()
    securityhub_summary = _get_securityhub_summary()

    # Generate report
    report = _generate_report(config_compliance, securityhub_summary, now)

    # Upload to S3
    key = f"reports/{now.strftime('%Y/%m')}/compliance-{now.strftime('%Y%m%d-%H%M')}.md"
    try:
        s3.put_object(Bucket=REPORT_BUCKET, Key=key, Body=report.encode(), ContentType="text/markdown")
        logger.info(f"Report uploaded to s3://{REPORT_BUCKET}/{key}")
    except Exception as e:
        logger.error(f"Upload failed: {e}")

    return {"statusCode": 200, "report_key": key, "report_length": len(report)}


def _get_config_compliance() -> dict[str, Any]:
    """Get AWS Config compliance summary."""
    try:
        response = config_client.get_compliance_summary_by_config_rule()
        summary = response.get("ComplianceSummary", {})
        return {
            "compliant": summary.get("CompliantResourceCount", {}).get("CappedCount", 0),
            "non_compliant": summary.get("NonCompliantResourceCount", {}).get("CappedCount", 0),
            "rules": _get_config_rules_detail(),
        }
    except Exception as e:
        logger.error(f"Config query failed: {e}")
        return {"compliant": 0, "non_compliant": 0, "rules": []}


def _get_config_rules_detail() -> list[dict]:
    """Get per-rule compliance status."""
    try:
        response = config_client.describe_compliance_by_config_rule()
        rules = []
        for rule in response.get("ComplianceByConfigRules", []):
            rules.append({
                "name": rule["ConfigRuleName"],
                "status": rule.get("Compliance", {}).get("ComplianceType", "UNKNOWN"),
            })
        return rules
    except Exception:
        return []


def _get_securityhub_summary() -> dict[str, Any]:
    """Get SecurityHub findings summary."""
    try:
        response = securityhub.get_findings(
            Filters={"WorkflowStatus": [{"Value": "NEW", "Comparison": "EQUALS"}]},
            MaxResults=100,
        )
        findings = response.get("Findings", [])
        by_severity = {}
        for f in findings:
            sev = f.get("Severity", {}).get("Label", "UNKNOWN")
            by_severity[sev] = by_severity.get(sev, 0) + 1
        return {"total": len(findings), "by_severity": by_severity}
    except Exception as e:
        logger.error(f"SecurityHub query failed: {e}")
        return {"total": 0, "by_severity": {}}


def _generate_report(config: dict, hub: dict, now: datetime) -> str:
    """Generate Markdown compliance report."""
    total_rules = len(config["rules"])
    compliant = sum(1 for r in config["rules"] if r["status"] == "COMPLIANT")
    score = (compliant / total_rules * 100) if total_rules > 0 else 0

    lines = [
        f"# SentinelGuard Compliance Report",
        f"**Generated:** {now.strftime('%Y-%m-%d %H:%M UTC')}",
        f"",
        f"## Executive Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Compliance Score | **{score:.0f}%** |",
        f"| Config Rules Compliant | {compliant}/{total_rules} |",
        f"| Open Security Findings | {hub['total']} |",
        f"| Critical Findings | {hub['by_severity'].get('CRITICAL', 0)} |",
        f"| High Findings | {hub['by_severity'].get('HIGH', 0)} |",
        f"",
        f"## AWS Config Rule Status",
        f"",
        f"| Rule | Status |",
        f"|------|--------|",
    ]

    for rule in sorted(config["rules"], key=lambda r: r["status"]):
        icon = "✅" if rule["status"] == "COMPLIANT" else "❌"
        lines.append(f"| {rule['name']} | {icon} {rule['status']} |")

    lines.extend([
        f"",
        f"## SecurityHub Findings by Severity",
        f"",
    ])

    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"]:
        count = hub["by_severity"].get(sev, 0)
        if count > 0:
            lines.append(f"- **{sev}:** {count}")

    lines.extend([
        f"",
        f"---",
        f"*Report generated by SentinelGuard — AWS Security & Compliance Baseline*",
    ])

    return "\n".join(lines)
