name: "CloudForge — Terraform CI/CD"

on:
  push:
    branches: [main]
    paths: ["cloudforge/**"]
  pull_request:
    branches: [main]
    paths: ["cloudforge/**"]

env:
  TF_VERSION: "1.6.0"
  WORKING_DIR: "./cloudforge"

permissions:
  id-token: write
  contents: read

jobs:
  lint:
    name: "Lint & Validate"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "${{ env.TF_VERSION }}" }
      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ${{ env.WORKING_DIR }}
      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: ${{ env.WORKING_DIR }}
      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

  plan:
    name: "Plan"
    needs: lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "${{ env.TF_VERSION }}" }
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan
        working-directory: ${{ env.WORKING_DIR }}

  apply:
    name: "Apply"
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "${{ env.TF_VERSION }}" }
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ env.WORKING_DIR }}
